// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: stats_request.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestKind int32

const (
	RequestKind_UnknownReqKind       RequestKind = 0
	RequestKind_InternalUnary        RequestKind = 1
	RequestKind_InternalSubscription RequestKind = 2
	RequestKind_Local                RequestKind = 3
	RequestKind_Cached               RequestKind = 4
	RequestKind_Unary                RequestKind = 5
	RequestKind_Subscription         RequestKind = 6
)

// Enum value maps for RequestKind.
var (
	RequestKind_name = map[int32]string{
		0: "UnknownReqKind",
		1: "InternalUnary",
		2: "InternalSubscription",
		3: "Local",
		4: "Cached",
		5: "Unary",
		6: "Subscription",
	}
	RequestKind_value = map[string]int32{
		"UnknownReqKind":       0,
		"InternalUnary":        1,
		"InternalSubscription": 2,
		"Local":                3,
		"Cached":               4,
		"Unary":                5,
		"Subscription":         6,
	}
)

func (x RequestKind) Enum() *RequestKind {
	p := new(RequestKind)
	*p = x
	return p
}

func (x RequestKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestKind) Descriptor() protoreflect.EnumDescriptor {
	return file_stats_request_proto_enumTypes[0].Descriptor()
}

func (RequestKind) Type() protoreflect.EnumType {
	return &file_stats_request_proto_enumTypes[0]
}

func (x RequestKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestKind.Descriptor instead.
func (RequestKind) EnumDescriptor() ([]byte, []int) {
	return file_stats_request_proto_rawDescGZIP(), []int{0}
}

type ResponseKind int32

const (
	ResponseKind_UnknownRespKind ResponseKind = 0
	ResponseKind_Ok              ResponseKind = 1
	ResponseKind_Cancelled       ResponseKind = 2
	ResponseKind_Error           ResponseKind = 3
	ResponseKind_RetryableError  ResponseKind = 4
	ResponseKind_RoutingError    ResponseKind = 5
)

// Enum value maps for ResponseKind.
var (
	ResponseKind_name = map[int32]string{
		0: "UnknownRespKind",
		1: "Ok",
		2: "Cancelled",
		3: "Error",
		4: "RetryableError",
		5: "RoutingError",
	}
	ResponseKind_value = map[string]int32{
		"UnknownRespKind": 0,
		"Ok":              1,
		"Cancelled":       2,
		"Error":           3,
		"RetryableError":  4,
		"RoutingError":    5,
	}
)

func (x ResponseKind) Enum() *ResponseKind {
	p := new(ResponseKind)
	*p = x
	return p
}

func (x ResponseKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseKind) Descriptor() protoreflect.EnumDescriptor {
	return file_stats_request_proto_enumTypes[1].Descriptor()
}

func (ResponseKind) Type() protoreflect.EnumType {
	return &file_stats_request_proto_enumTypes[1]
}

func (x ResponseKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseKind.Descriptor instead.
func (ResponseKind) EnumDescriptor() ([]byte, []int) {
	return file_stats_request_proto_rawDescGZIP(), []int{1}
}

type StatsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*StatsEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsBatch) Reset() {
	*x = StatsBatch{}
	mi := &file_stats_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsBatch) ProtoMessage() {}

func (x *StatsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_stats_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsBatch.ProtoReflect.Descriptor instead.
func (*StatsBatch) Descriptor() ([]byte, []int) {
	return file_stats_request_proto_rawDescGZIP(), []int{0}
}

func (x *StatsBatch) GetEntries() []*StatsEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StatsEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *StatsKey              `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data          *RequestStatsData      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsEntry) Reset() {
	*x = StatsEntry{}
	mi := &file_stats_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsEntry) ProtoMessage() {}

func (x *StatsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_stats_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsEntry.ProtoReflect.Descriptor instead.
func (*StatsEntry) Descriptor() ([]byte, []int) {
	return file_stats_request_proto_rawDescGZIP(), []int{1}
}

func (x *StatsEntry) GetKey() *StatsKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StatsEntry) GetData() *RequestStatsData {
	if x != nil {
		return x.Data
	}
	return nil
}

type StatsKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UpstreamId    string                 `protobuf:"bytes,2,opt,name=upstream_id,json=upstreamId,proto3" json:"upstream_id,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ReqKind       RequestKind            `protobuf:"varint,5,opt,name=req_kind,json=reqKind,proto3,enum=stats.RequestKind" json:"req_kind,omitempty"`
	RespKind      ResponseKind           `protobuf:"varint,6,opt,name=resp_kind,json=respKind,proto3,enum=stats.ResponseKind" json:"resp_kind,omitempty"`
	Chain         int64                  `protobuf:"varint,7,opt,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsKey) Reset() {
	*x = StatsKey{}
	mi := &file_stats_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsKey) ProtoMessage() {}

func (x *StatsKey) ProtoReflect() protoreflect.Message {
	mi := &file_stats_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsKey.ProtoReflect.Descriptor instead.
func (*StatsKey) Descriptor() ([]byte, []int) {
	return file_stats_request_proto_rawDescGZIP(), []int{2}
}

func (x *StatsKey) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StatsKey) GetUpstreamId() string {
	if x != nil {
		return x.UpstreamId
	}
	return ""
}

func (x *StatsKey) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *StatsKey) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *StatsKey) GetReqKind() RequestKind {
	if x != nil {
		return x.ReqKind
	}
	return RequestKind_UnknownReqKind
}

func (x *StatsKey) GetRespKind() ResponseKind {
	if x != nil {
		return x.RespKind
	}
	return ResponseKind_UnknownRespKind
}

func (x *StatsKey) GetChain() int64 {
	if x != nil {
		return x.Chain
	}
	return 0
}

type RequestStatsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestAmount int64                  `protobuf:"varint,1,opt,name=request_amount,json=requestAmount,proto3" json:"request_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestStatsData) Reset() {
	*x = RequestStatsData{}
	mi := &file_stats_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestStatsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStatsData) ProtoMessage() {}

func (x *RequestStatsData) ProtoReflect() protoreflect.Message {
	mi := &file_stats_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStatsData.ProtoReflect.Descriptor instead.
func (*RequestStatsData) Descriptor() ([]byte, []int) {
	return file_stats_request_proto_rawDescGZIP(), []int{3}
}

func (x *RequestStatsData) GetRequestAmount() int64 {
	if x != nil {
		return x.RequestAmount
	}
	return 0
}

var File_stats_request_proto protoreflect.FileDescriptor

const file_stats_request_proto_rawDesc = "" +
	"\n" +
	"\x13stats_request.proto\x12\x05stats\"9\n" +
	"\n" +
	"StatsBatch\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.stats.StatsEntryR\aentries\"\\\n" +
	"\n" +
	"StatsEntry\x12!\n" +
	"\x03key\x18\x01 \x01(\v2\x0f.stats.StatsKeyR\x03key\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.stats.RequestStatsDataR\x04data\"\xf1\x01\n" +
	"\bStatsKey\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vupstream_id\x18\x02 \x01(\tR\n" +
	"upstreamId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12-\n" +
	"\breq_kind\x18\x05 \x01(\x0e2\x12.stats.RequestKindR\areqKind\x120\n" +
	"\tresp_kind\x18\x06 \x01(\x0e2\x13.stats.ResponseKindR\brespKind\x12\x14\n" +
	"\x05chain\x18\a \x01(\x03R\x05chain\"9\n" +
	"\x10RequestStatsData\x12%\n" +
	"\x0erequest_amount\x18\x01 \x01(\x03R\rrequestAmount*\x82\x01\n" +
	"\vRequestKind\x12\x12\n" +
	"\x0eUnknownReqKind\x10\x00\x12\x11\n" +
	"\rInternalUnary\x10\x01\x12\x18\n" +
	"\x14InternalSubscription\x10\x02\x12\t\n" +
	"\x05Local\x10\x03\x12\n" +
	"\n" +
	"\x06Cached\x10\x04\x12\t\n" +
	"\x05Unary\x10\x05\x12\x10\n" +
	"\fSubscription\x10\x06*k\n" +
	"\fResponseKind\x12\x13\n" +
	"\x0fUnknownRespKind\x10\x00\x12\x06\n" +
	"\x02Ok\x10\x01\x12\r\n" +
	"\tCancelled\x10\x02\x12\t\n" +
	"\x05Error\x10\x03\x12\x12\n" +
	"\x0eRetryableError\x10\x04\x12\x10\n" +
	"\fRoutingError\x10\x05B\aZ\x05/;apib\x06proto3"

var (
	file_stats_request_proto_rawDescOnce sync.Once
	file_stats_request_proto_rawDescData []byte
)

func file_stats_request_proto_rawDescGZIP() []byte {
	file_stats_request_proto_rawDescOnce.Do(func() {
		file_stats_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_request_proto_rawDesc), len(file_stats_request_proto_rawDesc)))
	})
	return file_stats_request_proto_rawDescData
}

var file_stats_request_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_stats_request_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stats_request_proto_goTypes = []any{
	(RequestKind)(0),         // 0: stats.RequestKind
	(ResponseKind)(0),        // 1: stats.ResponseKind
	(*StatsBatch)(nil),       // 2: stats.StatsBatch
	(*StatsEntry)(nil),       // 3: stats.StatsEntry
	(*StatsKey)(nil),         // 4: stats.StatsKey
	(*RequestStatsData)(nil), // 5: stats.RequestStatsData
}
var file_stats_request_proto_depIdxs = []int32{
	3, // 0: stats.StatsBatch.entries:type_name -> stats.StatsEntry
	4, // 1: stats.StatsEntry.key:type_name -> stats.StatsKey
	5, // 2: stats.StatsEntry.data:type_name -> stats.RequestStatsData
	0, // 3: stats.StatsKey.req_kind:type_name -> stats.RequestKind
	1, // 4: stats.StatsKey.resp_kind:type_name -> stats.ResponseKind
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_stats_request_proto_init() }
func file_stats_request_proto_init() {
	if File_stats_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_request_proto_rawDesc), len(file_stats_request_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stats_request_proto_goTypes,
		DependencyIndexes: file_stats_request_proto_depIdxs,
		EnumInfos:         file_stats_request_proto_enumTypes,
		MessageInfos:      file_stats_request_proto_msgTypes,
	}.Build()
	File_stats_request_proto = out.File
	file_stats_request_proto_goTypes = nil
	file_stats_request_proto_depIdxs = nil
}
