upstream-config:
  upstreams:
    - id: cosmos-upstream
      chain: cosmos-hub
      head-connector: tendermint
      connectors:
        - type: tendermint
          url: https://cosmos-rpc.publicnode.com
