upstream-config:
  chain-defaults:
    sei:
      options:
        internal-timeout: 15s
        validate-syncing: true
        validate-call-limit: true
        call-limit-size: 2500000
  upstreams:
    - id: sei-upstream
      chain: sei
      connectors:
        - type: json-rpc
          url: https://test.com
